<!-- History Controls -->
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default modern-panel">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-history"></i> История генераций фида
					<div class="pull-right">
						<button type="button" id="btn-refresh-history" class="btn btn-xs btn-outline-dark">
							<i class="fa fa-refresh"></i> Обновить
						</button>
						<button type="button" id="btn-clear-history" class="btn btn-xs btn-outline-danger">
							<i class="fa fa-trash"></i> Очистить историю
						</button>
					</div>
				</h3>
			</div>
			<div class="panel-body">

				<!-- History Stats -->
				<div class="history-stats">
					<div class="row">
						<div class="col-md-3">
							<div class="stat-box stat-total">
								<div class="stat-number" id="total-generations">-</div>
								<div class="stat-label">Всего генераций</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="stat-box stat-success">
								<div class="stat-number" id="successful-generations">-</div>
								<div class="stat-label">Успешных</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="stat-box stat-error">
								<div class="stat-number" id="failed-generations">-</div>
								<div class="stat-label">С ошибками</div>
							</div>
						</div>
						<div class="col-md-3">
							<div class="stat-box stat-avg">
								<div class="stat-number" id="avg-time">-</div>
								<div class="stat-label">Среднее время</div>
							</div>
						</div>
					</div>
				</div>

				<!-- History Table -->
				<div class="history-table-container">
					<div class="table-responsive">
						<table class="table table-bordered table-hover" id="history-table">
							<thead>
							<tr>
								<th width="15%">
									<i class="fa fa-calendar"></i> Дата
								</th>
								<th width="10%">
									<i class="fa fa-info-circle"></i> Статус
								</th>
								<th width="12%">
									<i class="fa fa-shopping-cart"></i> Товаров
								</th>
								<th width="12%">
									<i class="fa fa-tags"></i> Предложений
								</th>
								<th width="10%">
									<i class="fa fa-clock-o"></i> Время
								</th>
								<th width="10%">
									<i class="fa fa-database"></i> Память
								</th>
								<th width="10%">
									<i class="fa fa-file-o"></i> Размер
								</th>
								<th width="21%">
									<i class="fa fa-cogs"></i> Действия
								</th>
							</tr>
							</thead>
							<tbody id="history-tbody">
							<tr>
								<td colspan="8" class="text-center">
									<div class="loading-spinner">
										<i class="fa fa-spinner fa-spin"></i> Загрузка истории...
									</div>
								</td>
							</tr>
							</tbody>
						</table>
					</div>
				</div>

				<!-- Pagination -->
				<div class="history-pagination">
					<nav>
						<ul class="pagination pagination-sm" id="history-pagination">
							<!-- Pagination will be generated by JS -->
						</ul>
					</nav>
				</div>

			</div>
		</div>
	</div>
</div>